# Generated by Django 5.0.7 on 2024-07-23 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviesdata_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviesdata',
            old_name='type',
            new_name='typ',
        ),
    ]
