# Generated by Django 4.2 on 2024-07-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_type_moviesdata_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesdata',
            name='image',
            field=models.ImageField(default='/Images/None/Noimg.jpg', upload_to='Images/'),
        ),
    ]
